(() => {
  'use strict';
  const S = window.CrocsStore;
  const $ = (selector, parent = document) => parent.querySelector(selector);
  const $$ = (selector, parent = document) => [...parent.querySelectorAll(selector)];
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const copy = value => JSON.parse(JSON.stringify(value));
  const labels = { dashboard: 'Tổng quan', orders: 'Đơn hàng', products: 'Sản phẩm', catalog: 'Catalog', collections: 'Bộ sưu tập', inventory: 'Tồn kho', themes: 'Giao diện', navigation: 'Menu', customers: 'Khách hàng', analytics: 'Báo cáo', marketing: 'Chiến dịch', settings: 'Cài đặt' };
  const statusNames = { Active: 'Đang bán', Draft: 'Bản nháp', Archived: 'Lưu trữ', paid: 'Đã thanh toán', pending: 'Chờ thanh toán', refunded: 'Đã hoàn tiền', fulfilled: 'Đã xử lý', unfulfilled: 'Chưa xử lý', cancelled: 'Đã hủy' };
  let data = S.read();
  let route = labels[location.hash.slice(1)] ? location.hash.slice(1) : 'dashboard';
  let query = '', statusFilter = '', stockFilter = '', period = 'all', sort = 'newest', page = 1;
  let selected = new Set(), menuId = data.settings.mainMenuId, menuDraft = null, toastTimer;
  let settingsTab = 'general', livePreview, savedFocus;
  const pageSize = 6;
  const main = $('#adminMain');
  const sidebar = $('#adminSidebar');
  const scrim = $('#adminScrim');
  const dialog = document.createElement('dialog');
  dialog.id = 'editorDialog'; dialog.className = 'studio-dialog'; document.body.append(dialog);
  const status = name => `<span class="status status--${({ Active: 'active', Draft: 'draft', Archived: 'refunded', paid: 'paid', pending: 'pending', refunded: 'refunded', fulfilled: 'fulfilled', unfulfilled: 'pending', cancelled: 'refunded' })[name] || 'draft'}">${esc(statusNames[name] || name)}</span>`;
  const date = value => new Intl.DateTimeFormat('vi-VN', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
  const btn = (text, action, attrs = '', kind = 'quiet') => `<button type="button" class="button button--${kind}" data-action="${action}" ${attrs}>${text}</button>`;
  const options = (list, value) => list.map(([id, name]) => `<option value="${esc(id)}" ${String(id) === String(value) ? 'selected' : ''}>${esc(name)}</option>`).join('');
  const field = (name, label, value = '', attrs = '') => `<label class="field"><span>${label}</span><input name="${name}" value="${esc(value)}" ${attrs}></label>`;
  const selectField = (name, label, values, value = '') => `<label class="field"><span>${label}</span><select name="${name}">${options(values, value)}</select></label>`;
  const textField = (name, label, value = '') => `<label class="field"><span>${label}</span><textarea name="${name}" rows="3">${esc(value)}</textarea></label>`;
  const heading = (title, description, actions = '') => `<div class="view-heading"><div><p class="view-kicker">Crocs · Admin studio</p><h1>${title}</h1><p class="view-description">${description}</p></div><div class="heading-actions">${actions}</div></div>`;
  const empty = (message = 'Chưa có dữ liệu phù hợp. Thử đổi bộ lọc hoặc thêm mục mới.') => `<div class="empty-state"><span>◌</span><h3>Không tìm thấy kết quả</h3><p>${message}</p>${btn('Xóa bộ lọc', 'clear-filters')}</div>`;
  const thumb = product => `<span class="product-thumb product-thumb--cream"><img src="${esc(product.image)}" alt="" loading="lazy"></span>`;
  function toast(message) {
    const target = $('#adminToast'); target.textContent = message; target.classList.add('is-visible');
    clearTimeout(toastTimer); toastTimer = setTimeout(() => target.classList.remove('is-visible'), 4200);
  }
  function commit(fn, message) {
    data = S.commit(fn, message);
    render();
    toast(message);
    // Persist the same validated state to Supabase without blocking the UI.
    window.CrocsBackend?.sync(data, message);
  }
  function dirty() { return Boolean($('form[data-dirty="true"]', main)); }
  function navigate(next) {
    if (!labels[next]) return;
    if (dirty() && !confirm('Bạn có thay đổi chưa lưu. Rời màn hình và bỏ các thay đổi này?')) return;
    route = next; query = ''; statusFilter = ''; stockFilter = ''; period = 'all'; sort = 'newest'; page = 1; selected.clear(); menuDraft = null;
    history.replaceState(null, '', `#${route}`); setSidebar(false); render(); window.scrollTo({ top: 0, behavior: 'instant' });
  }
  function setSidebar(open) {
    sidebar.classList.toggle('is-open', open); scrim.hidden = !open;
    $('#mobileMenuButton').setAttribute('aria-expanded', String(open));
    sidebar.inert = !open && matchMedia('(max-width:980px)').matches;
    document.body.classList.toggle('drawer-open', open);
    if (open) { savedFocus = document.activeElement; $('button', sidebar).focus(); }
    else if (savedFocus) { savedFocus.focus(); savedFocus = null; }
  }
  function formDialog(title, markup, onSave, saveText = 'Lưu thay đổi') {
    dialog.innerHTML = `<form id="editorForm"><header class="drawer-heading"><div><p class="panel-kicker">Lưu trên trình duyệt này</p><h2 id="dialogTitle">${title}</h2></div><button type="button" class="icon-button" data-close-dialog aria-label="Đóng">×</button></header><div class="dialog-body">${markup}<p class="form-error" role="alert" hidden></p></div><footer class="dialog-actions">${btn('Hủy', 'close-dialog')}<button class="button button--green" type="submit">${saveText}</button></footer></form>`;
    dialog.setAttribute('aria-labelledby', 'dialogTitle'); dialog.showModal();
    const form = $('#editorForm');
    form.onsubmit = async event => {
      event.preventDefault(); const submit = $('[type=submit]', form); submit.disabled = true;
      try { await onSave(new FormData(form), form); dialog.close(); }
      catch (error) { const box = $('.form-error', form); box.textContent = error.message; box.hidden = false; box.scrollIntoView({ block: 'nearest' }); }
      finally { submit.disabled = false; }
    };
  }
  function infoDialog(title, markup) {
    dialog.innerHTML = `<header class="drawer-heading"><h2 id="dialogTitle">${title}</h2><button type="button" class="icon-button" data-close-dialog aria-label="Đóng">×</button></header><div class="dialog-body">${markup}</div><footer class="dialog-actions">${btn('Đóng', 'close-dialog')}</footer>`;
    dialog.setAttribute('aria-labelledby', 'dialogTitle'); dialog.showModal();
  }
  function filtered() {
    let rows = [...(route === 'catalog' ? data.collections : route === 'inventory' ? data.products : data[route] || data.products)];
    const term = query.toLocaleLowerCase();
    rows = rows.filter(row => JSON.stringify([row.title, row.sku, row.name, row.email, row.category, row.number, row.customerName, row.customerEmail]).toLocaleLowerCase().includes(term));
    if (statusFilter) rows = rows.filter(row => row.status === statusFilter || row.payment === statusFilter || row.fulfillment === statusFilter);
    if (stockFilter === 'low') rows = rows.filter(p => p.stock <= data.settings.stockThreshold && p.status !== 'Archived');
    if (period !== 'all') rows = rows.filter(row => Date.now() - Date.parse(row.createdAt) <= Number(period) * 86400000);
    if (sort === 'title') rows.sort((a, b) => (a.title || a.name || '').localeCompare(b.title || b.name || ''));
    if (sort === 'price') rows.sort((a, b) => (a.price ?? S.total(a)) - (b.price ?? S.total(b)));
    if (sort === 'stock') rows.sort((a, b) => a.stock - b.stock);
    return rows;
  }
  function toolbar(kind) {
    const order = kind === 'orders';
    const filters = order ? [['', 'Mọi trạng thái'], ['unfulfilled', 'Chưa xử lý'], ['fulfilled', 'Đã xử lý'], ['paid', 'Đã thanh toán'], ['pending', 'Chờ thanh toán'], ['refunded', 'Hoàn tiền'], ['cancelled', 'Đã hủy']] : [['', 'Mọi trạng thái'], ['Active', 'Đang bán'], ['Draft', 'Bản nháp'], ['Archived', 'Lưu trữ']];
    const sortList = order ? [['newest', 'Mới nhất'], ['price', 'Tổng tiền tăng dần']] : [['newest', 'Gần đây'], ['title', 'Tên A–Z'], ...(kind === 'products' || kind === 'inventory' ? [['stock', 'Tồn kho tăng dần'], ['price', 'Giá tăng dần']] : [])];
    return `<div class="toolbar"><label class="table-search"><span aria-hidden="true">⌕</span><input id="tableQuery" type="search" data-search="table" aria-label="Tìm ${esc(labels[kind] || kind)}" placeholder="Tìm theo tên, mã…" value="${esc(query)}"></label><div class="toolbar-actions">${kind !== 'customers' && kind !== 'collections' ? `<select class="filter-button" data-filter="status" aria-label="Lọc trạng thái">${options(filters, statusFilter)}</select>` : ''}${order ? `<select class="filter-button" data-filter="period" aria-label="Khoảng ngày">${options([['all', 'Tất cả ngày'], ['7', '7 ngày qua'], ['30', '30 ngày qua']], period)}</select>` : kind === 'inventory' ? `<select class="filter-button" data-filter="stock" aria-label="Lọc tồn kho">${options([['', 'Mọi tồn kho'], ['low', 'Sắp hết hàng']], stockFilter)}</select>` : ''}<select class="filter-button" data-filter="sort" aria-label="Sắp xếp">${options(sortList, sort)}</select>${btn('CSV ↓', 'export')}</div></div>`;
  }
  function table(heads, rows) { return `<div class="table-scroll"><table class="data-table"><thead><tr>${heads.map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`; }
  function paginate(rows) {
    const count = Math.max(1, Math.ceil(rows.length / pageSize)); page = Math.min(page, count);
    const slice = rows.slice((page - 1) * pageSize, page * pageSize);
    return { slice, footer: `<div class="table-pagination"><span>${rows.length ? `${(page - 1) * pageSize + 1}–${Math.min(page * pageSize, rows.length)}` : '0'} / ${rows.length} kết quả</span><div>${btn('←', 'page', `data-delta="-1" aria-label="Trang trước" ${page === 1 ? 'disabled' : ''}`)}<span>${page}/${count}</span>${btn('→', 'page', `data-delta="1" aria-label="Trang sau" ${page === count ? 'disabled' : ''}`)}</div></div>` };
  }
  const rowSelect = id => `<input type="checkbox" data-select="${esc(id)}" aria-label="Chọn ${esc(id)}" ${selected.has(id) ? 'checked' : ''}>`;
  function renderProducts() {
    const rows = filtered(); const { slice, footer } = paginate(rows);
    const health = window.CrocsProducts?.health?.(data.products, data.settings.stockThreshold) || { variants: 0, low: [], seo: [] };
    const summary = [['Đang bán', data.products.filter(p => p.status === 'Active').length, 'summary-symbol--green', '◒'], ['SKU biến thể', health.variants, 'summary-symbol--blue', '⌁'], ['Cần SEO', health.seo.length, 'summary-symbol--yellow', '!'], ['Sắp hết hàng', health.low.length, 'summary-symbol--purple', '↘'], ['Bộ sưu tập', data.collections.length, 'summary-symbol--green', '○']];
    return heading('Sản phẩm', 'Từ nội dung, biến thể đến SEO — một catalog có thể vận hành, không chỉ là danh sách.', `${btn('Nhập JSON', 'import-products')}${btn('Thêm sản phẩm', 'add-product', '', 'green')}`) + `<div class="product-summary">${summary.map(([label, value, symbol, glyph]) => `<article><span class="summary-symbol ${symbol}">${glyph}</span><div><strong>${value}</strong><span>${label}</span></div></article>`).join('')}</div><div class="catalog-health"><button type="button" data-action="add-product">+ Tạo sản phẩm có biến thể</button><button type="button" data-action="seo-products">${health.seo.length ? `${health.seo.length} sản phẩm cần hoàn thiện SEO` : 'SEO catalog đã ổn'}</button><button type="button" data-action="low-variant-stock">${health.low.length ? `${health.low.length} dòng variant sắp hết` : 'Tồn variant ổn định'}</button></div><section class="panel management-panel">${toolbar('products')}<div class="bulk-bar" ${selected.size ? '' : 'hidden'}>${selected.size} đã chọn ${btn('Lưu trữ đã chọn', 'archive-selected')}</div>${slice.length ? table(['<input type="checkbox" data-select-page aria-label="Chọn cả trang">', 'Sản phẩm', 'Trạng thái', 'Tồn kho', 'Danh mục', 'Giá từ', ''], slice.map(p => `<tr><td>${rowSelect(p.id)}</td><td><button class="product-cell" data-action="edit-product" data-id="${esc(p.id)}">${thumb(p)}<span><strong>${esc(p.title)}</strong><small>${esc(p.sku)}${p.variants?.length ? ` · ${p.variants.length} biến thể` : ''}</small></span></button></td><td>${status(p.status)}</td><td><strong class="${p.stock <= data.settings.stockThreshold ? 'inventory-low' : ''}">${p.stock}</strong></td><td>${esc(p.category)}</td><td><strong>${S.money(p.price)}</strong></td><td>${btn('Sửa', 'edit-product', `data-id="${esc(p.id)}"`)}</td></tr>`)) : empty()}${footer}</section>`;
  }
  function productEditor(id = '') {
    const p = data.products.find(product => product.id === id) || {
      id: '', title: '', sku: '', description: '', price: 0, stock: 0, status: 'Draft', category: 'Clogs', image: 'assets/arrival-classic-clog-100.png', imageAlt: '', brand: 'Crocs', tags: [], slug: '', seo: { title: '', description: '', noindex: false }, options: [], variants: []
    };
    CrocsProductEditor.open({
      mount: main,
      product: p,
      products: data.products,
      collections: data.collections,
      onClose: () => render(),
      onSave: async (item, collectionIds) => {
        const nextItem = { ...item, id: id || S.id('product'), updatedAt: new Date().toISOString() };
        commit(next => {
          const index = next.products.findIndex(existing => existing.id === id);
          if (id && index < 0) throw new Error('Không tìm thấy sản phẩm.');
          if (index >= 0) next.products[index] = nextItem;
          else next.products.unshift(nextItem);
          next.collections.forEach(collection => { collection.productIds = collection.productIds.filter(productId => productId !== nextItem.id); });
          new Set(collectionIds).forEach(collectionId => next.collections.find(collection => collection.id === collectionId)?.productIds.push(nextItem.id));
        }, `Đã lưu ${nextItem.title}`);
      }
    });
  }
  function renderCollections(catalog = false) {
    const rows = catalog ? data.collections : filtered();
    const cards = rows.map(c => `<article class="catalog-card"><div class="collection-mosaic">${c.productIds.slice(0, 3).map(pid => { const p = data.products.find(p => p.id === pid); return p ? `<img src="${esc(p.image)}" alt="${esc(p.title)}">` : ''; }).join('') || '<span>Chưa có sản phẩm</span>'}</div><div class="catalog-copy">${status(c.status)}<h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><footer><span>${c.productIds.length} sản phẩm</span>${btn('Quản lý', 'edit-collection', `data-id="${esc(c.id)}"`)}</footer></div></article>`).join('');
    return heading(catalog ? 'Catalog' : 'Bộ sưu tập', 'Nhóm sản phẩm theo phong cách, mùa và bộ sưu tập trên storefront.', btn('Tạo bộ sưu tập', 'add-collection', '', 'green')) + (catalog ? `<div class="catalog-grid">${cards || empty()}</div>` : `<section class="panel management-panel">${toolbar('collections')}${rows.length ? table(['Bộ sưu tập', 'Sản phẩm', 'Trạng thái', ''], rows.map(c => `<tr><td><strong>${esc(c.title)}</strong><small class="inventory-note">${esc(c.description)}</small></td><td>${c.productIds.length}</td><td>${status(c.status)}</td><td>${btn('Sửa', 'edit-collection', `data-id="${esc(c.id)}"`)}</td></tr>`)) : empty()}</section>`);
  }
  function collectionEditor(id = '') {
    const c = data.collections.find(c => c.id === id) || { title: '', description: '', status: 'Draft', productIds: [] };
    formDialog(id ? 'Sửa bộ sưu tập' : 'Tạo bộ sưu tập', `${field('title', 'Tên bộ sưu tập', c.title, 'required maxlength="100"')}${textField('description', 'Mô tả', c.description)}${selectField('status', 'Trạng thái', [['Active', 'Công khai'], ['Draft', 'Bản nháp']], c.status)}<fieldset class="product-picker"><legend>Sản phẩm trong bộ sưu tập</legend>${data.products.map(p => `<label><input type="checkbox" name="productIds" value="${esc(p.id)}" ${c.productIds.includes(p.id) ? 'checked' : ''}>${thumb(p)}<span>${esc(p.title)}<small>${esc(statusNames[p.status])}</small></span></label>`).join('')}</fieldset>${id ? btn('Xóa bộ sưu tập', 'delete-collection', `data-id="${esc(id)}"`, 'danger') : ''}`, fd => {
      const item = { id: id || S.id('collection'), title: String(fd.get('title')).trim(), description: fd.get('description'), status: fd.get('status'), productIds: fd.getAll('productIds') };
      commit(next => { const i = next.collections.findIndex(c => c.id === id); if (i < 0) next.collections.push(item); else next.collections[i] = item; }, `Đã lưu ${item.title}`);
    });
  }
  function renderInventory() {
    const rows = filtered(); const { slice, footer } = paginate(rows);
    const reserved = pid => data.orders.filter(o => o.fulfillment === 'unfulfilled' && o.stockReserved).reduce((sum, o) => sum + o.items.filter(i => i.productId === pid).reduce((n, i) => n + i.quantity, 0), 0);
    return heading('Tồn kho', 'Tồn khả dụng đã trừ hàng giữ cho đơn mới. Hủy đơn chưa xử lý sẽ hoàn tồn.', btn('Điều chỉnh tồn', 'inventory-adjust', '', 'green')) + `<section class="panel management-panel">${toolbar('inventory')}${slice.length ? table(['Sản phẩm', 'SKU', 'Khả dụng', 'Đang giữ', ''], slice.map(p => `<tr><td><div class="product-cell">${thumb(p)}<strong>${esc(p.title)}</strong></div></td><td>${esc(p.sku)}</td><td><strong class="${p.stock <= data.settings.stockThreshold ? 'inventory-low' : ''}">${p.stock}</strong></td><td>${reserved(p.id)}</td><td>${btn('Điều chỉnh', 'inventory-adjust', `data-id="${esc(p.id)}"`)}</td></tr>`)) : empty()}${footer}</section>`;
  }
  function inventoryEditor(id = '') {
    const p = data.products.find(p => p.id === id) || data.products[0]; if (!p) return toast('Hãy thêm sản phẩm trước.');
    formDialog('Điều chỉnh tồn kho', `${selectField('productId', 'Sản phẩm', data.products.map(p => [p.id, `${p.title} · ${p.stock} khả dụng`]), p.id)}${field('stock', 'Tồn khả dụng mới', p.stock, 'type="number" min="0" step="1" max="1000000" required')}${field('reason', 'Lý do điều chỉnh', '', 'required placeholder="Nhập thêm hàng / kiểm kê…"')}`, fd => commit(next => { next.products.find(p => p.id === fd.get('productId')).stock = Number(fd.get('stock')); }, `Đã điều chỉnh tồn: ${fd.get('reason')}`));
    $('[name=productId]', dialog).onchange = event => { $('[name=stock]', dialog).value = data.products.find(p => p.id === event.target.value).stock; };
  }
  function orderRows(rows, checkboxes = true) { return rows.map(o => `<tr>${checkboxes ? `<td>${rowSelect(o.id)}</td>` : ''}<td><button class="table-link" data-action="order-detail" data-id="${esc(o.id)}">#${o.number}</button></td><td>${esc(o.customerName)}</td><td>${date(o.createdAt)}</td><td>${status(o.payment)}</td><td>${status(o.fulfillment)}</td><td><strong>${S.money(S.total(o))}</strong></td></tr>`); }
  function renderOrders() {
    const rows = filtered(); const { slice, footer } = paginate(rows);
    return heading('Đơn hàng', 'Theo dõi và xử lý đơn mẫu. Không thu tiền, gửi email hay tạo vận đơn thật.', btn('Tạo đơn hàng', 'new-order', '', 'green')) + `<div class="subnav-tabs" aria-label="Lọc đơn hàng">${[['', 'Tất cả'], ['unfulfilled', 'Chưa xử lý'], ['fulfilled', 'Đã xử lý'], ['pending', 'Chờ thanh toán']].map(([key, name]) => `<button class="subnav-tab ${statusFilter === key ? 'is-active' : ''}" data-order-filter="${key}" aria-pressed="${statusFilter === key}">${name} <b>${data.orders.filter(o => !key || o.payment === key || o.fulfillment === key).length}</b></button>`).join('')}</div><section class="panel management-panel">${toolbar('orders')}<div class="bulk-bar" ${selected.size ? '' : 'hidden'}>${selected.size} đã chọn ${btn('Đánh dấu đã xử lý', 'bulk-fulfill')}</div>${slice.length ? table(['<input type="checkbox" data-select-page aria-label="Chọn cả trang">', 'Mã đơn', 'Khách hàng', 'Ngày tạo', 'Thanh toán', 'Xử lý', 'Tổng cộng'], orderRows(slice)) : empty()}${footer}</section>`;
  }
  function orderDetail(id) {
    const o = data.orders.find(o => o.id === id); if (!o) return;
    infoDialog(`Đơn hàng #${o.number}`, `<div class="detail-summary"><div><strong>${esc(o.customerName)}</strong><p>${esc(o.customerEmail)}</p><small>${date(o.createdAt)} · ${esc(o.channel)}</small></div><div>${status(o.payment)} ${status(o.fulfillment)}</div></div>${table(['Sản phẩm', 'SL', 'Đơn giá', 'Thành tiền'], o.items.map(i => `<tr><td>${esc(i.title)}</td><td>${i.quantity}</td><td>${S.money(i.price)}</td><td>${S.money(i.price * i.quantity)}</td></tr>`))}<div class="order-totals"><span>Phí giao hàng</span><strong>${S.money(o.shipping)}</strong><span>Tổng cộng</span><strong>${S.money(S.total(o))}</strong></div><p class="local-note">Thao tác bên dưới chỉ cập nhật sổ đơn trên trình duyệt; không chuyển tiền hay liên hệ khách hàng.</p><div class="order-actions">${o.payment === 'pending' && o.fulfillment !== 'cancelled' ? btn('Đã nhận thanh toán', 'order-pay', `data-id="${id}"`, 'green') : ''}${o.payment === 'paid' && o.fulfillment === 'unfulfilled' ? btn('Đánh dấu đã xử lý', 'order-fulfill', `data-id="${id}"`, 'green') : ''}${o.fulfillment === 'unfulfilled' ? btn('Hủy đơn & hoàn tồn', 'order-cancel', `data-id="${id}"`) : ''}${o.payment === 'paid' ? btn('Ghi nhận hoàn tiền', 'order-refund', `data-id="${id}"`) : ''}</div><form id="orderNoteForm">${textField('note', 'Ghi chú nội bộ', o.note)}<button class="button button--quiet" type="submit">Lưu ghi chú</button></form>`);
    $('#orderNoteForm').onsubmit = event => { event.preventDefault(); commit(next => { next.orders.find(o => o.id === id).note = new FormData(event.currentTarget).get('note'); }, `Đã lưu ghi chú #${o.number}`); };
  }
  function newOrder() {
    if (!data.customers.length || !data.products.some(p => p.status === 'Active' && p.stock > 0)) return toast('Cần khách hàng và sản phẩm đang bán còn hàng.');
    formDialog('Tạo đơn hàng cục bộ', `${selectField('customerId', 'Khách hàng', data.customers.map(c => [c.id, `${c.name} · ${c.email}`]))}<fieldset class="order-lines"><legend>Sản phẩm</legend><div id="orderLines"></div>${btn('+ Thêm dòng', 'order-add-line')}</fieldset><p id="orderEstimate" class="order-estimate"></p>${field('shipping', 'Phí giao hàng (£)', '0.00', 'type="number" min="0" step="0.01" required')}${textField('note', 'Ghi chú')}<p class="local-note">Đơn mới ở trạng thái chờ thanh toán. Số lượng được trừ khỏi tồn khả dụng ngay khi lưu.</p>`, (fd, form) => {
      const lines = $$('.order-line', form).map(row => ({ productId: $('[name=productId]', row).value, quantity: Number($('[name=quantity]', row).value) }));
      commit(next => S.createOrder(next, fd.get('customerId'), lines, fd.get('note'), Math.round(Number(fd.get('shipping')) * 100)), 'Đã tạo đơn và giữ tồn kho');
    }, 'Tạo đơn');
    addOrderLine();
  }
  function addOrderLine() { $('#orderLines')?.insertAdjacentHTML('beforeend', `<div class="order-line"><select name="productId" aria-label="Sản phẩm">${options(data.products.filter(p => p.status === 'Active' && p.stock > 0).map(p => [p.id, `${p.title} · ${S.money(p.price)} · Còn ${p.stock}`]))}</select><input name="quantity" type="number" min="1" max="100000" step="1" value="1" required aria-label="Số lượng"><button type="button" class="icon-button" data-action="order-remove-line" aria-label="Bỏ dòng">×</button></div>`); orderEstimate(); }
  function orderEstimate() { const output = $('#orderEstimate'); if (output) output.textContent = `Tiền hàng: ${S.money($$('.order-line', dialog).reduce((sum, row) => sum + (data.products.find(p => p.id === $('[name=productId]', row).value)?.price || 0) * Number($('[name=quantity]', row).value), 0))}`; }
  function renderCustomers() {
    const rows = filtered(); const { slice, footer } = paginate(rows);
    return heading('Khách hàng', 'Hồ sơ, ghi chú và lịch sử mua hàng. Email mẫu không được sử dụng để gửi thư.', btn('Thêm khách hàng', 'add-customer', '', 'green')) + `<section class="panel management-panel">${toolbar('customers')}${slice.length ? table(['Khách hàng', 'Email', 'Thành phố', 'Đơn hàng', 'Đã chi', ''], slice.map(c => { const orders = data.orders.filter(o => o.customerId === c.id); return `<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.email)}</td><td>${esc(c.city)}</td><td>${orders.length}</td><td>${S.money(orders.filter(o => o.payment === 'paid' && o.fulfillment !== 'cancelled').reduce((sum, o) => sum + S.total(o), 0))}</td><td>${btn('Hồ sơ', 'edit-customer', `data-id="${esc(c.id)}"`)}</td></tr>`; })) : empty()}${footer}</section>`;
  }
  function customerEditor(id = '') {
    const c = data.customers.find(c => c.id === id) || { name: '', email: '', city: '', phone: '', note: '', marketing: false };
    formDialog(id ? 'Hồ sơ khách hàng' : 'Thêm khách hàng', `${field('name', 'Họ tên', c.name, 'required maxlength="100"')}${field('email', 'Email', c.email, 'type="email" required')}<div class="form-grid">${field('city', 'Thành phố', c.city)}${field('phone', 'Số điện thoại', c.phone, 'type="tel"')}</div>${textField('note', 'Ghi chú', c.note)}${id ? `<h3>Lịch sử đơn hàng</h3><div class="customer-order-links">${data.orders.filter(o => o.customerId === id).map(o => `<span>#${o.number} · ${S.money(S.total(o))} · ${esc(statusNames[o.payment])}</span>`).join('') || '<p>Chưa có đơn hàng.</p>'}</div>` : ''}`, fd => {
      const item = { ...c, id: id || S.id('customer'), name: String(fd.get('name')).trim(), email: String(fd.get('email')).trim(), city: fd.get('city'), phone: fd.get('phone'), note: fd.get('note'), createdAt: c.createdAt || new Date().toISOString() };
      commit(next => { const index = next.customers.findIndex(c => c.id === id); if (index < 0) next.customers.push(item); else next.customers[index] = item; }, `Đã lưu ${item.name}`);
    });
  }
  function metrics(days = 7) {
    const within = data.orders.filter(o => Date.now() - Date.parse(o.createdAt) < days * 86400000);
    const paid = within.filter(o => o.payment === 'paid' && o.fulfillment !== 'cancelled');
    const sales = paid.reduce((sum, o) => sum + S.total(o), 0);
    const daily = Array.from({ length: days }, (_, index) => { const day = new Date(); day.setDate(day.getDate() - (days - index - 1)); const key = day.toLocaleDateString('en-CA'); return { label: day.toLocaleDateString('vi-VN', { day: 'numeric', month: 'numeric' }), value: paid.filter(o => new Date(o.createdAt).toLocaleDateString('en-CA') === key).reduce((sum, o) => sum + S.total(o), 0) }; });
    return { within, paid, sales, daily, avg: paid.length ? sales / paid.length : 0, units: paid.reduce((n, o) => n + o.items.reduce((n, i) => n + i.quantity, 0), 0) };
  }
  function cards(m) { return `<div class="metric-grid">${[['Doanh thu đã ghi nhận', S.money(m.sales), 'Đơn đã thanh toán, không hủy'], ['Đơn hàng', m.within.length, 'Tất cả trạng thái trong kỳ'], ['Sản phẩm bán', m.units, 'Từ đơn đã thanh toán'], ['Giá trị đơn trung bình', S.money(m.avg), `${m.paid.length} đơn đã thanh toán`]].map(([label, value, note], i) => `<article class="metric-card ${i === 0 ? 'metric-card--green' : ''}"><div class="metric-top"><span>${label}</span><span>↗</span></div><strong>${value}</strong><p>${note}</p></article>`).join('')}</div>`; }
  function chart(m) {
    const max = Math.max(100, ...m.daily.map(d => d.value)); const points = m.daily.map((d, i) => `${20 + i / (m.daily.length - 1) * 680},${190 - d.value / max * 160}`).join(' ');
    return `<section class="panel sales-panel"><div class="panel-heading"><div><p class="panel-kicker">${m.daily.length} ngày qua · dữ liệu cục bộ</p><h2>Doanh thu theo ngày</h2></div><span>${S.money(m.sales)}</span></div><div class="chart-wrap"><svg viewBox="0 0 720 220" role="img" aria-label="Doanh thu hàng ngày" class="sales-chart"><path class="chart-grid" d="M20 30H700M20 110H700M20 190H700"/><polygon class="chart-area" points="20,190 ${points} 700,190"/><polyline class="chart-line" points="${points}"/></svg><div class="chart-x-labels">${m.daily.map(d => `<span>${d.label}</span>`).join('')}</div></div><details class="chart-data"><summary>Xem số liệu từng ngày</summary><div>${m.daily.map(d => `<span>${d.label}<strong>${S.money(d.value)}</strong></span>`).join('')}</div></details></section>`;
  }
  function activityList() { return data.activity.slice(0, 6).map(a => `<div class="activity-item"><span class="activity-mark activity-mark--order">✓</span><p><strong>${esc(a.title)}</strong><span>${date(a.createdAt)}</span></p></div>`).join(''); }
  function renderDashboard() {
    const m = metrics(7), low = data.products.filter(p => p.stock <= data.settings.stockThreshold && p.status !== 'Archived');
    return heading('Chào mừng trở lại.', `${new Intl.DateTimeFormat('vi-VN', { dateStyle: 'full' }).format(new Date())} · Một góc nhìn về cửa hàng của bạn.`, `<a class="button button--quiet" href="index.html" target="_blank" rel="noopener">Xem cửa hàng ↗</a>${btn('Tạo đơn hàng', 'new-order', '', 'green')}`) + cards(m) + `<div class="dashboard-columns">${chart(m)}<section class="panel activity-panel"><div class="panel-heading"><div><p class="panel-kicker">Nhật ký quản trị</p><h2>Hoạt động gần đây</h2></div></div><div class="activity-list">${activityList()}</div>${btn('Xem nhật ký', 'activity')}</section></div><div class="insight-grid"><article class="insight-card insight-card--stock"><span class="summary-symbol summary-symbol--yellow">!</span><div><h3>${low.length} sản phẩm cần kiểm tra tồn</h3><p>Ngưỡng cảnh báo: ${data.settings.stockThreshold} sản phẩm khả dụng.</p>${btn('Xem tồn kho', 'low-stock')}</div></article><article class="insight-card insight-card--campaign"><img class="insight-campaign-image" src="assets/crocs-hero-mobile.jpg" alt="Cozy Favourites"><div><p class="panel-kicker">Giao diện hiện tại</p><h3>${esc(data.theme.published.heroTitle)}</h3><p>Tùy chỉnh ảnh, nội dung và bộ sưu tập.</p><button class="text-button" data-view="themes">Chỉnh giao diện →</button></div></article></div><section class="panel orders-preview"><div class="panel-heading"><h2>Đơn hàng gần đây</h2><button class="text-button" data-view="orders">Tất cả đơn →</button></div>${table(['Đơn', 'Khách hàng', 'Ngày tạo', 'Thanh toán', 'Xử lý', 'Tổng cộng'], orderRows(data.orders.slice(0, 5), false))}</section>`;
  }
  function renderAnalytics() { const m = metrics(30); const scores = new Map(); m.paid.forEach(o => o.items.forEach(i => { const item = scores.get(i.productId) || { title: i.title, quantity: 0, revenue: 0 }; item.quantity += i.quantity; item.revenue += i.quantity * i.price; scores.set(i.productId, item); })); return heading('Báo cáo', '30 ngày qua. Chỉ sử dụng sổ đơn cục bộ; chưa tích hợp lượt truy cập hay conversion.', btn('Xuất đơn CSV', 'export')) + cards(m) + `<div class="analytics-grid">${chart(m)}<section class="panel analytics-table"><div class="panel-heading"><h2>Sản phẩm bán chạy</h2></div>${table(['Sản phẩm', 'SL', 'Doanh thu'], [...scores.values()].sort((a, b) => b.revenue - a.revenue).slice(0, 6).map(p => `<tr><td>${esc(p.title)}</td><td>${p.quantity}</td><td>${S.money(p.revenue)}</td></tr>`))}</section></div>`; }
  function renderNavigation() {
    const active = data.menus.find(m => m.id === menuId) || data.menus[0]; menuId = active.id; if (!menuDraft || menuDraft.id !== menuId) menuDraft = copy(active);
    return heading('Menu điều hướng', 'Chỉnh liên kết, kéo để sắp xếp hoặc dùng nút ↑ ↓. Lưu để cập nhật storefront.', btn('Tạo menu', 'add-menu', '', 'green')) + `<div class="navigation-layout"><section class="panel menu-list-panel"><h2>Menu cửa hàng</h2>${data.menus.map(m => `<button class="menu-row ${m.id === menuId ? 'is-selected' : ''}" data-action="select-menu" data-id="${esc(m.id)}"><span>☰</span><span><strong>${esc(m.title)}</strong><small>${m.items.length} liên kết${m.id === data.settings.mainMenuId ? ' · Header' : ''}${m.id === data.settings.footerMenuId ? ' · Footer' : ''}</small></span><span>›</span></button>`).join('')}</section><form id="menuForm" class="panel menu-editor"><div class="panel-heading"><h2>${esc(active.title)}</h2><button class="button button--green" type="submit">Lưu menu</button></div>${field('menuTitle', 'Tên menu', menuDraft.title, 'required')}<div id="menuItems">${menuItemsMarkup()}</div><div class="menu-actions">${btn('+ Thêm liên kết', 'add-menu-item')}${![data.settings.mainMenuId, data.settings.footerMenuId].includes(menuId) ? btn('Xóa menu', 'delete-menu', `data-id="${esc(menuId)}"`, 'danger') : ''}</div><p class="local-note">Liên kết hỗ trợ #section của trang chủ và URL https://. Gán menu Header/Footer tại Cài đặt.</p></form></div>`;
  }
  function menuItemsMarkup() { return menuDraft.items.map((item, i) => `<div class="menu-edit-row" draggable="true" data-menu-row="${i}"><span class="drag-handle" aria-hidden="true">⋮⋮</span><div>${field('label', 'Nhãn', item.label, 'required maxlength="70"')}${field('url', 'Liên kết', item.url, 'required')}</div><div class="menu-row-actions">${btn('↑', 'menu-up', `data-index="${i}" aria-label="Chuyển lên" ${i === 0 ? 'disabled' : ''}`)}${btn('↓', 'menu-down', `data-index="${i}" aria-label="Chuyển xuống" ${i === menuDraft.items.length - 1 ? 'disabled' : ''}`)}${btn('×', 'menu-remove', `data-index="${i}" aria-label="Xóa liên kết"`)}</div></div>`).join(''); }
  function renderThemes() {
    const t = data.theme.draft;
    return heading('Giao diện cửa hàng', 'Chỉnh bản nháp, xem trước, rồi xuất bản cho storefront cùng trình duyệt.', `<a href="index.html" target="_blank" rel="noopener" class="button button--quiet">Xem storefront ↗</a>`) + `<div class="theme-workspace"><form id="themeForm" class="panel theme-controls">${field('heroTitle', 'Tiêu đề hero', t.heroTitle, 'required maxlength="80"')}${field('heroSubtitle', 'Mô tả hero', t.heroSubtitle, 'maxlength="160"')}${field('heroButton', 'Nhãn nút mua sắm', t.heroButton, 'required maxlength="40"')}${textField('announcement', 'Thanh thông báo', t.announcement)}${selectField('campaign', 'Ảnh campaign', [['cozy', 'Cozy Favourites'], ['crocband', 'Crocband'], ['ninjago', 'LEGO Ninjago']], t.campaign)}<div class="form-grid">${field('accent', 'Màu thương hiệu', t.accent, 'type="color"')}${field('background', 'Nền danh mục', t.background, 'type="color"')}</div>${selectField('collectionId', 'Bộ sưu tập trên trang chủ', data.collections.filter(c => c.status === 'Active').map(c => [c.id, c.title]), t.collectionId)}<fieldset class="theme-sections"><legend>Hiển thị trên trang chủ</legend>${[['showClassics', 'Classic icons'], ['showArrivals', 'Sản phẩm mới'], ['showCollabs', 'Collaborations'], ['showClub', 'Crocs Club']].map(([key, label]) => `<label><input type="checkbox" name="${key}" ${t[key] ? 'checked' : ''}>${label}</label>`).join('')}</fieldset><div class="theme-save-actions"><button class="button button--quiet" type="submit">Lưu bản nháp</button>${btn('Xuất bản', 'publish-theme', '', 'green')}</div><p class="local-note">Đã xuất bản: ${date(data.theme.publishedAt)}. Xem trước không thay đổi storefront thật.</p></form><section class="panel theme-preview-panel"><header><strong>Xem trước tương tác</strong><div>${btn('Desktop', 'preview-desktop')}${btn('Mobile', 'preview-mobile')}</div></header><div class="preview-frame-wrap" id="previewWrap"><iframe id="storePreview" title="Xem trước storefront" src="index.html?preview=theme" loading="eager"></iframe></div></section></div>`;
  }
  function themeValues() { const fd = new FormData($('#themeForm')); const t = { ...data.theme.draft }; ['heroTitle', 'heroSubtitle', 'heroButton', 'announcement', 'campaign', 'accent', 'background', 'collectionId'].forEach(key => { t[key] = fd.get(key); }); ['showClassics', 'showArrivals', 'showCollabs', 'showClub'].forEach(key => { t[key] = fd.has(key); }); return t; }
  function sendPreview() { const frame = $('#storePreview'); if (frame && $('#themeForm')) frame.contentWindow.postMessage({ type: 'crocs:theme-preview', theme: themeValues() }, '*'); }
  function renderSettings() {
    const s = data.settings;
    const backend = window.CrocsBackend;
    const backendState = backend?.status === 'connected' ? 'Đang hoạt động' : backend?.status === 'offline' ? 'Offline · fallback cục bộ' : 'Đang kết nối…';
    return heading('Cài đặt', `Store state được lưu trong Supabase · ${backendState}`) + `<div class="settings-layout"><nav class="settings-menu" aria-label="Nhóm cài đặt">${[['general', 'Cửa hàng'], ['data', 'Dữ liệu & sao lưu'], ['integrations', 'Kết nối & bảo mật']].map(([key, text]) => `<button class="${key === settingsTab ? 'is-active' : ''}" data-action="settings-tab" data-id="${key}">${text}</button>`).join('')}</nav><section class="panel settings-panel">${settingsTab === 'general' ? `<form id="settingsForm"><h2>Thông tin cửa hàng</h2><div class="form-grid">${field('name', 'Tên cửa hàng', s.name, 'required maxlength="100"')}${field('email', 'Email cửa hàng', s.email, 'type="email" required')}${selectField('currency', 'Tiền tệ', [['GBP', 'GBP · British Pound']], s.currency)}${selectField('timezone', 'Múi giờ cửa hàng', [['Europe/London', 'London'], ['Asia/Ho_Chi_Minh', 'Việt Nam']], s.timezone)}${selectField('mainMenuId', 'Menu header', data.menus.map(m => [m.id, m.title]), s.mainMenuId)}${selectField('footerMenuId', 'Menu footer', data.menus.map(m => [m.id, m.title]), s.footerMenuId)}${field('stockThreshold', 'Cảnh báo tồn dưới hoặc bằng', s.stockThreshold, 'type="number" min="0" step="1" required')}</div><p class="local-note">Giữ GBP để bảo toàn giá và đơn đã lưu; thay đổi sẽ đồng bộ lên Supabase.</p><button class="button button--green" type="submit">Lưu cài đặt</button></form>` : settingsTab === 'data' ? `<h2>Dữ liệu & sao lưu</h2><p class="view-description">Tải tệp JSON để lưu trữ toàn bộ sản phẩm, đơn hàng, khách hàng, menu và theme của cửa hàng.</p><div class="data-actions">${btn('Tải bản sao JSON', 'backup', '', 'green')}${btn('Khôi phục từ JSON', 'restore')}</div><p class="local-note">Bản sao tải xuống là phương án dự phòng; dữ liệu chính được lưu trong Supabase. Không dùng dữ liệu khách hàng thật trong bản demo.</p>` : `<h2>Kết nối & bảo mật</h2><div class="integration-list">${[['Supabase database', backendState === 'Đang hoạt động' ? 'Đã kết nối store_state và audit events.' : 'Đang dùng fallback cho tới khi kết nối phục hồi.'], ['Đăng nhập & phân quyền', 'Chưa tích hợp Auth/team roles; trang admin vẫn mở công khai.'], ['Thanh toán & hoàn tiền', 'Chỉ ghi nhận trạng thái nội bộ; không kết nối cổng thanh toán.'], ['Giao hàng & email', 'Không tạo vận đơn, không gửi email hoặc thông báo khách hàng.']].map(([title, desc], index) => `<div><strong>${title}</strong><p>${desc}</p><span class="status status--${index === 0 && backendState === 'Đang hoạt động' ? 'active' : 'draft'}">${index === 0 ? backendState : 'Chưa kết nối'}</span></div>`).join('')}</div>`}</section></div>`;
  }
  function renderMarketing() { return heading('Chiến dịch', 'Lập kế hoạch nội dung. Bản local không gửi email hoặc chạy quảng cáo.', btn('Tạo chiến dịch', 'create-campaign', '', 'green')) + `<div class="campaign-grid">${data.campaigns.map(c => `<article class="campaign-card"><span class="campaign-status campaign-status--draft">Bản nháp</span><p class="panel-kicker">${esc(c.channel)}</p><h2>${esc(c.title)}</h2><p>${esc(c.subject)}</p><small>${c.date ? `Dự kiến: ${esc(c.date)}` : 'Chưa đặt ngày dự kiến'}</small>${btn('Chỉnh nội dung', 'edit-campaign', `data-id="${esc(c.id)}"`)}</article>`).join('') || empty()}</div>`; }
  function campaignEditor(id = '') { const c = data.campaigns.find(c => c.id === id) || { title: '', subject: '', content: '', channel: 'Email', date: '' }; formDialog('Nội dung chiến dịch', `${field('title', 'Tên nội bộ', c.title, 'required')}${selectField('channel', 'Kênh', [['Email', 'Email'], ['Social', 'Mạng xã hội'], ['Website', 'Website']], c.channel)}${field('subject', 'Tiêu đề', c.subject, 'required')}${textField('content', 'Nội dung', c.content)}${field('date', 'Ngày dự kiến (không tự động gửi)', c.date, 'type="date"')}`, fd => commit(next => { const item = { id: id || S.id('campaign'), title: fd.get('title'), subject: fd.get('subject'), content: fd.get('content'), date: fd.get('date'), channel: fd.get('channel'), status: 'Draft' }; const i = next.campaigns.findIndex(c => c.id === id); if (i < 0) next.campaigns.push(item); else next.campaigns[i] = item; }, 'Đã lưu bản nháp chiến dịch')); }
  function render() {
    const views = { dashboard: renderDashboard, products: renderProducts, orders: renderOrders, catalog: () => renderCollections(true), collections: () => renderCollections(), inventory: renderInventory, themes: renderThemes, navigation: renderNavigation, customers: renderCustomers, analytics: renderAnalytics, marketing: renderMarketing, settings: renderSettings };
    const backend = window.CrocsBackend;
    const backendStatus = backend?.status === 'connected' ? 'Đã kết nối Supabase' : backend?.status === 'offline' ? 'Offline · đang dùng bản lưu cục bộ' : backend?.status === 'disabled' ? 'Chưa cấu hình backend' : 'Đang kết nối Supabase…';
    const backendDetail = backend?.status === 'connected' ? 'Dữ liệu admin được đồng bộ qua Supabase' : backend?.status === 'offline' ? 'Thay đổi mới sẽ đồng bộ lại khi kết nối phục hồi' : 'State store JSONB · publishable key · RLS';
    main.innerHTML = `<div class="environment-banner"><span class="local-indicator"></span><strong>${backendStatus}</strong><span>${backendDetail}</span>${location.protocol === 'file:' ? '<span class="file-warning">Deploy Vercel hoặc mở localhost để dùng ổn định.</span>' : ''}</div>${S.storageIssue ? `<p class="form-error">${esc(S.storageIssue)}</p>` : ''}<section class="admin-view" data-view-panel="${route}">${views[route]()}</section>`;
    $('#breadcrumbLabel').textContent = labels[route]; $$('.sidebar-nav [data-view]').forEach(button => { const active = button.dataset.view === route; button.classList.toggle('is-active', active); if (active) button.setAttribute('aria-current', 'page'); else button.removeAttribute('aria-current'); });
    $('.nav-count').textContent = data.orders.filter(o => o.fulfillment === 'unfulfilled').length; $('.store-switcher-copy strong').textContent = data.settings.name; bindForms();
  }
  function bindForms() {
    const menuForm = $('#menuForm'); if (menuForm) menuForm.onsubmit = event => { event.preventDefault(); syncMenu(); try { commit(next => { next.menus[next.menus.findIndex(m => m.id === menuId)] = copy(menuDraft); }, 'Đã lưu menu và cập nhật storefront'); } catch (e) { toast(e.message); } };
    const themeForm = $('#themeForm'); if (themeForm) { themeForm.onsubmit = event => { event.preventDefault(); try { const t = themeValues(); commit(next => { next.theme.draft = t; }, 'Đã lưu bản nháp giao diện'); } catch (e) { toast(e.message); } }; $('#storePreview').onload = sendPreview; }
    const settingsForm = $('#settingsForm'); if (settingsForm) settingsForm.onsubmit = event => { event.preventDefault(); const fd = new FormData(settingsForm); try { commit(next => { next.settings = { ...next.settings, ...Object.fromEntries(fd), stockThreshold: Number(fd.get('stockThreshold')) }; }, 'Đã lưu cài đặt cửa hàng'); } catch (e) { toast(e.message); } };
  }
  function download(name, value, type) { const blob = new Blob([value], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function csvCell(value) { let text = String(value ?? ''); if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`; return `"${text.replace(/"/g, '""')}"`; }
  function exportCSV() {
    const source = route === 'orders' || route === 'analytics' ? data.orders : filtered(); let rows;
    if (route === 'orders' || route === 'analytics') rows = [['Order', 'Customer', 'Date', 'Payment', 'Fulfillment', 'Total GBP'], ...source.map(o => [o.number, o.customerName, o.createdAt, o.payment, o.fulfillment, (S.total(o) / 100).toFixed(2)])];
    else if (route === 'customers') rows = [['Name', 'Email', 'City', 'Phone'], ...source.map(c => [c.name, c.email, c.city, c.phone])];
    else if (route === 'collections') rows = [['Title', 'Status', 'Product count'], ...source.map(c => [c.title, c.status, c.productIds.length])];
    else rows = [['Product', 'SKU', 'Status', 'Stock', 'Price GBP'], ...source.map(p => [p.title, p.sku, p.status, p.stock, (p.price / 100).toFixed(2)])];
    download(`crocs-${route}.csv`, '\ufeff' + rows.map(row => row.map(csvCell).join(',')).join('\r\n'), 'text/csv;charset=utf-8'); toast('Đã tạo tệp CSV để tải xuống');
  }
  function importDialog(backup = false) { formDialog(backup ? 'Khôi phục dữ liệu' : 'Nhập sản phẩm JSON', `<p class="local-note">${backup ? 'Tệp sao lưu Crocs Studio v1. Thao tác thay thế dữ liệu cục bộ sau xác nhận.' : 'Mảng JSON gồm nội dung, SEO và options/variants. Giá lưu bằng pence; SKU trùng sẽ được cập nhật.'}</p>${field('file', 'Chọn tệp JSON (tối đa 2 MB)', '', 'type="file" accept=".json,application/json" required')}${!backup ? btn('Tải mẫu JSON', 'product-template') : ''}`, async fd => { const file = fd.get('file'); if (!file || file.size > 2 * 1024 * 1024) throw new Error('Chọn tệp JSON tối đa 2 MB.'); let parsed; try { parsed = JSON.parse(await file.text()); } catch { throw new Error('Không đọc được JSON. Kiểm tra định dạng tệp.'); } if (backup) { S.validate(parsed); if (!confirm('Thay thế toàn bộ dữ liệu trên trình duyệt bằng bản sao lưu này?')) return; data = S.save(parsed); menuDraft = null; render(); toast('Đã khôi phục bản sao lưu'); } else { if (!Array.isArray(parsed) || !parsed.length || parsed.length > 500) throw new Error('Tệp cần là mảng từ 1 đến 500 sản phẩm.'); if (!confirm(`Nhập ${parsed.length} sản phẩm? Các SKU trùng sẽ được cập nhật.`)) return; commit(next => parsed.forEach(p => { const existing = next.products.find(item => item.sku.toLowerCase() === String(p.sku).toLowerCase()); const item = { ...(existing || {}), id: existing?.id || S.id('product'), title: String(p.title || '').trim(), sku: String(p.sku || '').trim(), price: p.price, stock: p.stock, status: p.status || 'Draft', image: p.image || 'assets/arrival-classic-clog-100.png', imageAlt: p.imageAlt || `${p.title || 'Sản phẩm'} product image`, brand: p.brand || 'Crocs', category: p.category || 'Clogs', description: p.description || '', tags: Array.isArray(p.tags) ? p.tags.map(String) : [], slug: p.slug || '', seo: { title: '', description: '', noindex: false, ...(p.seo || {}) }, options: Array.isArray(p.options) ? p.options : [], variants: Array.isArray(p.variants) ? p.variants : [], updatedAt: new Date().toISOString() }; if (existing) next.products[next.products.indexOf(existing)] = item; else next.products.unshift(item); }), `Đã nhập ${parsed.length} sản phẩm`); } }, backup ? 'Kiểm tra & khôi phục' : 'Kiểm tra & nhập'); }
  function searchDialog() { infoDialog('Tìm trong quản trị', `${field('adminQuery', 'Tên sản phẩm, khách hàng hoặc mã đơn', '', 'type="search" placeholder="Classic, #1048, Olivia…"')}<div id="searchResults" class="search-results"></div>`); const input = $('[name=adminQuery]', dialog); input.focus(); const update = () => { const term = input.value.toLowerCase().replace(/^#/, ''); const results = [...Object.entries(labels).map(([id, title]) => ({ id, title, kind: 'nav', sub: 'Màn hình quản trị' })), ...data.products.map(p => ({ id: p.id, title: p.title, kind: 'product', sub: p.sku })), ...data.customers.map(c => ({ id: c.id, title: c.name, kind: 'customer', sub: c.email })), ...data.orders.map(o => ({ id: o.id, title: `#${o.number}`, kind: 'order', sub: o.customerName }))].filter(r => `${r.title} ${r.sub}`.toLowerCase().includes(term)).slice(0, 12); $('#searchResults').innerHTML = results.map(r => `<button data-action="search-result" data-kind="${r.kind}" data-id="${esc(r.id)}"><strong>${esc(r.title)}</strong><small>${esc(r.sub)}</small><span>↗</span></button>`).join('') || '<p>Không có kết quả phù hợp.</p>'; }; input.oninput = update; update(); }
  const actions = {
    'add-product': () => productEditor(), 'edit-product': el => productEditor(el.dataset.id), 'add-collection': () => collectionEditor(), 'edit-collection': el => collectionEditor(el.dataset.id), 'inventory-adjust': el => inventoryEditor(el.dataset.id), 'new-order': newOrder, 'order-detail': el => orderDetail(el.dataset.id), 'add-customer': () => customerEditor(), 'edit-customer': el => customerEditor(el.dataset.id), 'create-campaign': () => campaignEditor(), 'edit-campaign': el => campaignEditor(el.dataset.id), 'close-dialog': () => dialog.close(), 'focus-search': searchDialog, 'export': exportCSV,
    'clear-filters': () => { query = statusFilter = stockFilter = ''; period = 'all'; page = 1; selected.clear(); render(); }, 'page': el => { page += Number(el.dataset.delta); selected.clear(); render(); },
    'archive-product': el => { if (confirm('Lưu trữ sản phẩm? Sản phẩm sẽ không còn hiển thị trên storefront.')) { commit(next => { next.products.find(p => p.id === el.dataset.id).status = 'Archived'; }, 'Đã lưu trữ sản phẩm'); dialog.close(); } }, 'archive-selected': () => { if (selected.size && confirm(`Lưu trữ ${selected.size} sản phẩm đã chọn?`)) { commit(next => next.products.forEach(p => { if (selected.has(p.id)) p.status = 'Archived'; }), 'Đã lưu trữ các sản phẩm'); selected.clear(); } }, 'delete-product': el => { if (!confirm('Xóa vĩnh viễn sản phẩm chưa có đơn hàng này?')) return; commit(next => { if (next.orders.some(o => o.items.some(i => i.productId === el.dataset.id))) throw new Error('Sản phẩm có lịch sử đơn hàng, hãy lưu trữ thay vì xóa.'); next.products = next.products.filter(p => p.id !== el.dataset.id); next.collections.forEach(c => { c.productIds = c.productIds.filter(id => id !== el.dataset.id); }); }, 'Đã xóa sản phẩm'); dialog.close(); }, 'delete-collection': el => { if (data.theme.published.collectionId === el.dataset.id || data.theme.draft.collectionId === el.dataset.id) throw new Error('Bộ sưu tập đang được dùng trong theme. Hãy chọn bộ sưu tập khác trước.'); if (confirm('Xóa bộ sưu tập? Sản phẩm bên trong được giữ lại.')) { commit(next => { next.collections = next.collections.filter(c => c.id !== el.dataset.id); }, 'Đã xóa bộ sưu tập'); dialog.close(); } },
    'bulk-fulfill': () => { if (!selected.size) return; commit(next => { selected.forEach(id => S.transitionOrder(next, id, 'fulfill')); }, 'Đã đánh dấu các đơn đã xử lý'); selected.clear(); }, 'order-add-line': addOrderLine, 'order-remove-line': el => { if ($$('.order-line', dialog).length < 2) return toast('Đơn cần ít nhất một dòng sản phẩm.'); el.closest('.order-line').remove(); orderEstimate(); }, 'low-stock': () => { navigate('inventory'); stockFilter = 'low'; render(); }, 'seo-products': () => { const model = window.CrocsProducts; if (!model) return toast('Trình kiểm tra SEO chưa sẵn sàng.'); const health = model.health(data.products); const missing = product => model.seoReport(product).filter(item => !item.ok).map(item => item.label); infoDialog('Checklist SEO catalog', `<p class="local-note">${health.seo.length ? 'Các sản phẩm dưới đây chưa đạt 6/7 gợi ý nội dung. Mở từng sản phẩm để chỉnh.' : 'Các sản phẩm đang có đủ trường nội dung cơ bản.'}</p><div class="full-activity">${health.seo.map(p => `<article><strong>${esc(p.title)}</strong><p>${esc(missing(p).join(' · '))}</p><button class="button button--quiet" data-action="search-result" data-kind="product" data-id="${esc(p.id)}">Mở trình biên tập</button></article>`).join('') || '<p>Không có cảnh báo SEO.</p>'}</div>`); }, 'low-variant-stock': () => { const model = window.CrocsProducts; if (!model) return toast('Trình kiểm tra biến thể chưa sẵn sàng.'); const health = model.health(data.products, data.settings.stockThreshold); infoDialog('Variant sắp hết hàng', `<p class="local-note">Tồn khả dụng ≤ ${data.settings.stockThreshold} sẽ hiện ở đây để chỉnh nhanh.</p><div class="full-activity">${health.low.map(item => `<article><strong>${esc(item.title)}</strong><p>Còn ${item.stock}</p></article>`).join('') || '<p>Không có dòng nào sắp hết.</p>'}</div>`); },
    'select-menu': el => { if (dirty() && !confirm('Bỏ thay đổi menu chưa lưu?')) return; menuId = el.dataset.id; menuDraft = null; render(); }, 'add-menu': () => formDialog('Tạo menu', field('title', 'Tên menu', '', 'required'), fd => commit(next => { const item = { id: S.id('menu'), title: fd.get('title'), items: [] }; next.menus.push(item); menuId = item.id; menuDraft = null; }, 'Đã tạo menu')), 'add-menu-item': () => { syncMenu(); menuDraft.items.push({ id: S.id('link'), label: '', url: '#shop' }); $('#menuItems').innerHTML = menuItemsMarkup(); $('#menuForm').dataset.dirty = 'true'; }, 'delete-menu': el => { if ([data.settings.mainMenuId, data.settings.footerMenuId].includes(el.dataset.id)) throw new Error('Menu đang sử dụng, không thể xóa.'); if (confirm('Xóa menu này?')) commit(next => { next.menus = next.menus.filter(m => m.id !== el.dataset.id); menuId = next.settings.mainMenuId; menuDraft = null; }, 'Đã xóa menu'); },
    'publish-theme': () => { if (!$('#themeForm').reportValidity()) return; const t = themeValues(); commit(next => { next.theme.draft = copy(t); next.theme.published = copy(t); next.theme.publishedAt = new Date().toISOString(); }, 'Đã xuất bản giao diện cho storefront cục bộ'); }, 'preview-desktop': () => $('#previewWrap').classList.remove('is-mobile'), 'preview-mobile': () => $('#previewWrap').classList.add('is-mobile'), 'settings-tab': el => { if (dirty() && !confirm('Bỏ các thay đổi chưa lưu?')) return; settingsTab = el.dataset.id; render(); }, 'backup': () => { download('crocs-studio-backup.json', JSON.stringify(S.read(), null, 2), 'application/json'); toast('Đã tạo bản sao lưu'); }, 'restore': () => importDialog(true), 'import-products': () => importDialog(), 'product-template': () => download('products-template.json', JSON.stringify([{ title: 'Sample Clog', sku: 'SAMPLE-001', price: 3499, stock: 20, status: 'Draft', image: 'assets/arrival-classic-clog-100.png', category: 'Clogs', tags: [] }], null, 2), 'application/json'), 'notifications': () => infoDialog('Hoạt động gần đây', `<div class="activity-list">${activityList()}</div>`), 'activity': () => infoDialog('Nhật ký quản trị', `<div class="full-activity">${data.activity.map(a => `<article><strong>${esc(a.title)}</strong><p>${esc(a.detail)}</p><small>${date(a.createdAt)}</small></article>`).join('')}</div>`), 'store-switcher': () => infoDialog('Cửa hàng hiện tại', `<h3>${esc(data.settings.name)}</h3><p>Chỉ một cửa hàng cục bộ. Đổi tên và menu trong Cài đặt.</p>`), 'user-menu': () => infoDialog('Workspace cục bộ', '<p>Đây là tài khoản hiển thị mẫu, không phải phiên đăng nhập. Chưa có xác thực hoặc phân quyền. Không triển khai công khai trước khi thêm backend và bảo mật.</p>'), 'help': () => infoDialog('Bắt đầu với Admin Studio', '<ol><li>Thêm sản phẩm và chọn trạng thái Đang bán.</li><li>Nhóm sản phẩm vào Bộ sưu tập.</li><li>Chọn bộ sưu tập trong Giao diện rồi Xuất bản.</li><li>Tạo đơn để kiểm tra tồn kho và trạng thái.</li><li>Sao lưu JSON trong Cài đặt để giữ dữ liệu.</li></ol><p>Mọi thay đổi được lưu trong localStorage; không đồng bộ thiết bị hoặc tài khoản Shopify.</p>'), 'search-result': el => { dialog.close(); const action = { nav: () => navigate(el.dataset.id), product: () => productEditor(el.dataset.id), customer: () => customerEditor(el.dataset.id), order: () => orderDetail(el.dataset.id) }[el.dataset.kind]; action?.(); },
    'product-template': () => download('products-template.json', JSON.stringify([{ title: 'Sample Clog', sku: 'SAMPLE-001', price: 3499, stock: 20, status: 'Draft', image: 'assets/arrival-classic-clog-100.png', imageAlt: 'Sample Clog màu trắng nhìn nghiêng', brand: 'Crocs', category: 'Clogs', description: 'Mô tả sản phẩm tối thiểu 120 ký tự giúp người mua và công cụ tìm kiếm hiểu rõ chất liệu, phom dáng, cảm giác đi và cách phối mẫu này.', tags: ['clog', 'unisex'], slug: 'sample-clog', seo: { title: 'Sample Clog | Crocs UK', description: 'Khám phá Sample Clog nhẹ, êm và dễ phối đồ cho mọi ngày. Chọn màu và size phù hợp để bắt đầu.', noindex: false }, options: [{ id: 'colour', name: 'Màu sắc', values: ['Trắng', 'Đen'] }, { id: 'size', name: 'Size UK', values: ['5', '6', '7'] }], variants: [{ id: 'v-sample-clog-trang-5', values: { colour: 'Trắng', size: '5' }, sku: 'SAMPLE-001-WHT-5', price: 3499, compareAt: null, cost: 1500, stock: 10, enabled: true, barcode: '' }] }], null, 2), 'application/json'),
  };
  document.addEventListener('click', event => {
    const target = event.target.closest('button, a'); if (!target) return;
    if (target.hasAttribute('data-view')) return navigate(target.dataset.view);
    if (target.hasAttribute('data-close-dialog')) return dialog.close();
    if (target.hasAttribute('data-order-filter')) { statusFilter = target.dataset.orderFilter; page = 1; selected.clear(); return render(); }
    const action = target.dataset.action; if (!action) return;
    try {
      if (['order-pay', 'order-fulfill', 'order-cancel', 'order-refund'].includes(action)) { const op = action.replace('order-', ''); const messages = { pay: 'Ghi nhận thanh toán nội bộ, không thu tiền qua cổng thanh toán?', fulfill: 'Đánh dấu đơn đã xử lý? Không tạo vận đơn thật.', cancel: 'Hủy đơn chưa xử lý và hoàn số lượng vào tồn kho?', refund: 'Ghi nhận đã hoàn tiền bên ngoài? Không chuyển tiền tự động.' }; if (!confirm(messages[op])) return; commit(next => S.transitionOrder(next, target.dataset.id, op), 'Đã cập nhật trạng thái đơn hàng'); dialog.close(); orderDetail(target.dataset.id); }
      else if (['menu-up', 'menu-down', 'menu-remove'].includes(action)) { syncMenu(); const i = Number(target.dataset.index); if (action === 'menu-remove') menuDraft.items.splice(i, 1); else { const to = action === 'menu-up' ? i - 1 : i + 1; if (to >= 0 && to < menuDraft.items.length) [menuDraft.items[i], menuDraft.items[to]] = [menuDraft.items[to], menuDraft.items[i]]; } $('#menuItems').innerHTML = menuItemsMarkup(); $('#menuForm').dataset.dirty = 'true'; }
      else actions[action]?.(target);
    } catch (error) { toast(error.message); }
  });
  document.addEventListener('input', event => { const el = event.target; if (el.matches('[data-search=table]')) { query = el.value; page = 1; selected.clear(); render(); $('#tableQuery')?.focus(); } const form = el.closest('#menuForm, #themeForm, #settingsForm'); if (form) form.dataset.dirty = 'true'; if (el.closest('#themeForm')) { clearTimeout(livePreview); livePreview = setTimeout(sendPreview, 100); } if (el.closest('.order-line')) orderEstimate(); });
  document.addEventListener('change', event => { const el = event.target; if (el.matches('[data-filter]')) { const key = el.dataset.filter; if (key === 'status') statusFilter = el.value; if (key === 'stock') stockFilter = el.value; if (key === 'period') period = el.value; if (key === 'sort') sort = el.value; page = 1; selected.clear(); render(); } if (el.matches('[data-select]')) { if (el.checked) selected.add(el.dataset.select); else selected.delete(el.dataset.select); render(); } if (el.matches('[data-select-page]')) { $$('[data-select]', main).forEach(box => { if (el.checked) selected.add(box.dataset.select); else selected.delete(box.dataset.select); }); render(); } });
  function syncMenu() { menuDraft.title = $('[name=menuTitle]', main).value; menuDraft.items = $$('[data-menu-row]', main).map((row, i) => ({ id: menuDraft.items[i]?.id || S.id('link'), label: $('[name=label]', row).value, url: $('[name=url]', row).value })); }
  document.addEventListener('dragstart', event => { const row = event.target.closest('[data-menu-row]'); if (row) { syncMenu(); row.classList.add('is-dragging'); event.dataTransfer.setData('text/plain', row.dataset.menuRow); } });
  document.addEventListener('dragend', event => event.target.closest('[data-menu-row]')?.classList.remove('is-dragging'));
  document.addEventListener('dragover', event => { if (event.target.closest('[data-menu-row]')) event.preventDefault(); });
  document.addEventListener('drop', event => { const row = event.target.closest('[data-menu-row]'); if (!row) return; const from = Number(event.dataTransfer.getData('text/plain')); const to = Number(row.dataset.menuRow); if (Number.isNaN(from) || from === to) return; event.preventDefault(); const [item] = menuDraft.items.splice(from, 1); menuDraft.items.splice(to, 0, item); $('#menuItems').innerHTML = menuItemsMarkup(); $('#menuForm').dataset.dirty = 'true'; });
  $('#mobileMenuButton').onclick = () => setSidebar(!sidebar.classList.contains('is-open')); scrim.onclick = () => setSidebar(false); matchMedia('(max-width:980px)').addEventListener('change', () => setSidebar(false));
  document.addEventListener('keydown', event => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); if (!dialog.open) searchDialog(); } if (event.key === 'Escape' && sidebar.classList.contains('is-open')) setSidebar(false); if (event.key === 'Tab' && sidebar.classList.contains('is-open')) { const list = $$('button, a', sidebar); const first = list[0], last = list.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } });
  window.addEventListener('hashchange', () => { const next = location.hash.slice(1); if (labels[next]) navigate(next); });
  window.addEventListener('beforeunload', event => { if (dirty()) { event.preventDefault(); event.returnValue = ''; } });
  window.addEventListener('storage', event => { if (event.key === S.KEY) { data = S.read(); if (!dirty() && !dialog.open) { menuDraft = null; render(); } else toast('Dữ liệu đã đổi ở tab khác. Hãy tải lại trước khi lưu để tránh ghi đè.'); } });
  window.addEventListener('crocs:backend-ready', () => { data = S.read(); if (!dirty() && !dialog.open) { menuDraft = null; render(); } });
  window.addEventListener('crocs:backend-status', () => { if (!dirty() && !dialog.open) render(); });
  setSidebar(false); render();
})();
